export const FETCH_TICKETS = 'FETCH_TICKETS';
export const ADD_COLOURS = 'ADD_COLOURS';
export const FETCH_HALLS = 'FETCH_HALLS';
export const HANDLE_DATE_INPUT_SUBMIT = 'HANDLE_DATE_INPUT_SUBMIT';
export const UPPERBAR_BACKWARD_SWITCHER = 'UPPERBAR_BACKWARD_SWITCHER';
export const DETERMINE_RESERVED_SLOTS = 'DETERMINE_RESERVED_SLOTS'; 
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const INVOKE_FAILED_REGISTRATION_ERROR = 'INVOKE_FAILED_REGISTRATION_ERROR';